apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name  }} #from RELEASE NAME
spec:
  selector: 
    matchLabels:
      {{- include "spring.labels" . | nindent 2}}
      app: music  
  replicas: {{ .Values.pods.replicas }}  #from values
  template:
    metadata:
      labels:
        app: music
    spec:
      containers:
      - name: {{ .Values.service.name }} #from values
        image: {{ .Values.pods.imagename }}:{{ .Values.pods.imagetag }} #from values
        ports:
        - containerPort: 8080
